### ISSUE TITLE
ÇA PUSH AVEC LE CUL

### ISSUE THREAD

**Issue by tcarmet** [sboudouk/42#1]
wesh vous pusher les binaires... les .o 
c quoi ca? ? ? ? ? ? ?

**Comment by sboudouk** [comment]
mdrrr rentre chez toi

**Comment by tcarmet** [comment]
hahahaha nan serieusement tu peux pas laisser ça comme ça.... 
jvais montrer ca a flappy toute ta vie il va te charier...
